version: '3.4'

services:
  search:
    environment:
      NODE_ENV: test

  tasks:
    environment:
      NODE_ENV: test

  todo:
    environment:
      NODE_ENV: test

  todo-frontend:
    ports:
      - '13000:8080'

  postgres:
    ports:
      - '15432:5432' # in case we run the end-to-end tests on the host
