version: '3'

services:
  search:
    build:
      context: ..
      dockerfile: example/search/Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: 8080

  tasks:
    build:
      context: ..
      dockerfile: example/tasks/Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: 8080

  todo:
    build:
      context: ..
      dockerfile: example/todo/Dockerfile
    depends_on:
      - search
      - tasks
    environment:
      PORT: 8080

  postgres:
    image: postgres
