version: '3.4'

services:
  search:
    command: npx lzproxy
    volumes:
      - ../lzproxy:/opt/lzproxy
      - ./storage:/opt/storage
      - ./search:/opt/search
      - search_lzproxy_node_modules:/opt/lzproxy/node_modules
      - search_storage_node_modules:/opt/storage/node_modules
      - search_node_modules:/opt/search/node_modules

  tasks:
    command: npx lzproxy
    volumes:
      - ../lzproxy:/opt/lzproxy
      - ./storage:/opt/storage
      - ./tasks:/opt/tasks
      - tasks_lzproxy_node_modules:/opt/lzproxy/node_modules
      - tasks_storage_node_modules:/opt/storage/node_modules
      - tasks_node_modules:/opt/tasks/node_modules

  todo:
    build:
      context: ..
      dockerfile: example/todo/Dockerfile
      target: backend-dev
    command: npx lzproxy
    volumes:
      - ../lzproxy:/opt/lzproxy
      - ./storage:/opt/storage
      - ./todo/backend:/opt/todo/backend
      - todo_lzproxy_node_modules:/opt/lzproxy/node_modules
      - todo_storage_node_modules:/opt/storage/node_modules
      - todo_backend_node_modules:/opt/todo/backend/node_modules

  todo-frontend:
    build:
      context: ..
      dockerfile: example/todo/Dockerfile
      target: frontend
    depends_on:
      - todo
    env_file:
      - common.env
    volumes:
      - ./todo/frontend:/opt/todo/frontend
      - todo_frontend_node_modules:/opt/todo/frontend/node_modules

volumes:
  todo_lzproxy_node_modules:
  todo_storage_node_modules:
  todo_backend_node_modules:
  todo_frontend_node_modules:
  tasks_lzproxy_node_modules:
  tasks_storage_node_modules:
  tasks_node_modules:
  search_lzproxy_node_modules:
  search_storage_node_modules:
  search_node_modules:
