version: '3.4'

services:
  search:
    build:
      context: ..
      dockerfile: example/search/Dockerfile
    depends_on:
      - postgres
    env_file:
      - common.env

  tasks:
    build:
      context: ..
      dockerfile: example/tasks/Dockerfile
    depends_on:
      - postgres
    env_file:
      - common.env

  todo:
    build:
      context: ..
      dockerfile: example/todo/Dockerfile
      target: backend
    depends_on:
      - search
      - tasks
    env_file:
      - common.env
    environment:
      SERVICE_PORT: 8080

  postgres:
    image: postgres
