version: 2

lzproxy-build: &lzproxy-build
  steps:
    - checkout

    - restore_cache:
        keys:
          - root-dependencies-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "./package-lock.json" }}
    - run: npm install -q
    - save_cache:
        key: root-dependencies-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "./package-lock.json" }}
        paths:
          - ./node_modules

    - restore_cache:
        keys:
          - lzproxy-dependencies-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "./lzproxy/package-lock.json" }}
    - run: cd lzproxy && npm install -q
    - save_cache:
        key: lzproxy-dependencies-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "./lzproxy/package-lock.json" }}
        paths:
          - ./lzproxy/node_modules

    - run: npm run lint

    - run: cd lzproxy && npm test

jobs:
  node-10:
    <<: *lzproxy-build
    docker:
      - image: circleci/node:10

  node-12:
    <<: *lzproxy-build
    docker:
      - image: circleci/node:12

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-12
